<?php // "Incidentes/block template ?>
        <!-- This is from the $sidebarBlockView View Model, and the
            "Incidentes/block" template -->
        <div class="block" style="background-color: red">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus molestie venenatis dui ut sagittis. Phasellus vel orci dolor. Pellentesque enim nisi, dignissim ut nunc eget, accumsan rhoncus odio. Sed sagittis sapien sapien, in faucibus justo venenatis in. Pellentesque id sapien at metus euismod cursus et sit amet justo. Donec ultricies, sapien blandit laoreet dignissim, enim elit ullamcorper libero, nec lobortis nunc neque vitae quam. Mauris luctus viverra ullamcorper. Pellentesque id pulvinar sem.

Suspendisse blandit ante in fringilla mattis. Aenean elementum ultrices urna dictum eleifend. Sed at lobortis tellus. Cras rutrum urna id mollis fermentum. Integer non varius neque. Morbi quis diam luctus, ultricies purus finibus, euismod ipsum. Fusce condimentum pharetra purus, eget porttitor ipsum mollis ut. Nunc sed dolor auctor, aliquam diam et, auctor tellus. Vivamus quis gravida mi. Pellentesque non ante metus.

Mauris et hendrerit nibh. Nulla a convallis erat. Nulla nec sagittis metus.
        </div>