<?php
    $container = $this->container;
    $it = new RecursiveIteratorIterator($container, RecursiveIteratorIterator::SELF_FIRST);
    echo "<ul class='".$this->navigation($container)->menu()->getUlClass()."' >";
    $mayor=0;
    $limite=array();
    foreach ($it as $page)
    {
        if($page->class=='')
        {
            $limite[]=$mayor;
            $mayor=0;                        
        }
        if((int)$page->class>$mayor)
        {
            $mayor=$page->class;
        }
        echo $page->class;
    }
    $limite[]=$mayor;
    unset($limite[0]);
    $limite=array_values($limite);
    echo "<br>".print_r($limite,true);
    echo "<br>".  sizeof($limite);
    $cantidadLiPrincipal=0;
    $ul=0;
    foreach ($it as $page)
    {        
        if($page->class=='' && $page->uri=='#')
        {
            echo "<li class='dropdown'>";
            echo "<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>";
            echo $page->label;          
            echo "<span class='caret'></span></a>";
            echo "<ul class='dropdown-menu' role='menu'>";
        }
        if($page->class=='0')
        {
            if($it->callHasChildren())
            {
                
            }
            else
            {
                if($page->route)
                    $link=$page->route;
                else
                    $link=$page->uri;
                echo "  <li><a href='$link'>".$page->label."</a></li>";
            }
            echo "</ul>";
        }
        
    }
    
    function submenus(){
        
    }
    /*foreach ($it as $page) {
        $pnivel=FALSE;
        $snivel=FALSE;
        if($page->class=='')
        {   
            $pnivel=TRUE;
            echo "<li class='dropdown'>";
            echo "<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>";
            echo $page->label;          
            echo "<span class='caret'></span></a>";
        }
        if($page->class!='0')
            echo "<ul class='dropdown-menu' role='menu'>";
        if($page->class=='0' && !$page->callHasChildren())
        {     
            $snivel=TRUE;
            if($page->route)
                $link=$page->route;
            else
                $link=$page->uri;
            echo "  <li><a href='$link'>".$page->label."</a></li>";
        }
        if($page->class=='0' && $page->callHasChildren())
        {
            echo "<ul class='dropdown-submenu' >";
        }
        
        if($page->class!='0' && $snivel==TRUE)
            echo "</ul>";
        
        
        
        
        if($page->class!='' && $pnivel==TRUE)
            echo "</li>";
    }
    echo "</ul>";*/
?>